version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .build/app
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - .:/var/www/html
      - ./.env:/var/www/html/.env
    env_file:
      - .env

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: guest
      MYSQL_PASSWORD: guest
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
